### ISSUE TITLE
Make importing tab more solid

### ISSUE THREAD

**Issue by xMartin** [xMartin/grouptabs#102]
Importing a tab (open existing) should fail with feedback when the backend cannot be reached or when the ID is not valid (tab does not exist). Currently the behavior is undefined.

**Comment by jancborchardt** [comment]
Some additional points:
- [ ] make sure the field doesn’t force autocapitalization for the first letter
- [ ] regardless of that, the ID input should be case-_in_sensitive
- [ ] provide some loading feedback (e.g. a spinner) while the values aren’t shown yet

Ran into that when joining a shared tab with an iOS device.

**Comment by xMartin** [comment]
Done by 0bfddb235eadba616ef99746b31eb1aafb87f6f8, 68218f9be561268d7fd4fba834bc0a6d9bbee53d, c00cea4de3cffc55ee55034b932c75bdf825d5cf

**Comment by jancborchardt** [comment]
Check it out @reginasipos, your feedback helped to improve software ;)
