### ISSUE TITLE
Autofocus transaction description

### ISSUE THREAD

**Issue by jancborchardt** [xMartin/grouptabs#105]
When regularly putting in transactions it becomes a bit cumbersome to tap the description input manually each time.

It should be autofocused. Maybe not for the very first transaction so you get an overview of the inputs. But for all subsequent ones for sure.

**Comment by xMartin** [comment]
Not sure. You might want to enter date or participants first.

**Comment by jancborchardt** [comment]
Most likely though is that you want to enter a description though. Participants will in most cases already exist (unless you want to add someone new or it’s the first transaction. And the date is set to the current day by default.

But in all cases the description is the only missing thing, and of course who paid and which amount. Since we know for certain the description field, but not who paid, autofocusing that would be of help.

At least when using Grouptabs regularly it’s quite helpful. We can always see if it turns out to be more of a drag than being useful. But not doing anything is also a bit strange. :)

**Comment by xMartin** [comment]
I don't see how not focussing anything when displaying a form is strange.

Anyway, fair enough, let's try it out.
