### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jancborchardt** [xMartin/grouptabs#107]
While running npm install I just discovered that the license info is missing.
And it’s nowhere to be found …

@xMartin we are working on practically closed-source software! How can you do this to me? :scream: 

Let’s use AGPL. (Or if you don’t like that, MIT.) What do you think?

**Comment by xMartin** [comment]
I know. Sorry! :)

I still cannot decide for GPL or MIT/BSD...

AGPL is not really needed as we're not running any code on the server, I do I get it wrong?

**Comment by jancborchardt** [comment]
Not sure if it’s really needed for client-side only apps. But it’s very widely used for web apps so I would take that anyway.

Maybe @schiessle can advise?

**Comment by jancborchardt** [comment]
Not sure if it’s really needed for client-side only apps. But it’s very widely used for web apps so I would take that anyway.

Maybe @schiessle or @hugoroy can advise?

**Comment by schiessle** [comment]
> AGPL is not really needed as we're not running any code on the server, I do I get it wrong?

Compared to the GPL, the AGPL "just" has a extended definition on when someone has the right to get the source code. If the software doesn't run on the server but only on local systems there is basically no difference between GPL and AGPL. So if you don't run any code on the server and it doesn't really is an option, neither for you nor for any 3rd party, it doesn't matter which license you chose.

If you would ask me, I would recommend to use the GPLv3 or AGPLv3 (whatever you like more) and to use the licenses as they are, don't remove the "or any later version" part.

**Comment by hugoroy** [comment]
Exactly. If it's a client-side only app, there's virtually no point in
applying the AGPL over the GPL.

In that case GPL has upsides: it's more common and easier to understand.

**Comment by jancborchardt** [comment]
@xMartin I’d strongly suggest that we use the GPLv3+ then over MIT/BSD. :)

**Comment by xMartin** [comment]
Ok :)
