### ISSUE TITLE
Travis builds fail

### ISSUE THREAD

**Issue by jancborchardt** [xMartin/grouptabs#110]
For example: https://travis-ci.org/xMartin/grouptabs/builds/206537868

We don’t have a travis.yml and it fails with:
```
$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by xMartin** [comment]
I set the following option in travis so shouldn't happen any more:

> Build only if .travis.yml is present

Will setup travis for building and linting later.

**Comment by jancborchardt** [comment]
Cool!
