### ISSUE TITLE
Automatically create config.js file on first run

### ISSUE THREAD

**Issue by jancborchardt** [xMartin/grouptabs#113]
The current step 2 of the setup says:

> 2. Copy `js/config-sample.js` to `js/config.js`

We should automate that through either carrying it out in the `npm install` step or a future possible `npm run serve` – ref #112 (add web server as nodejs dependency).

**Comment by jancborchardt** [comment]
@xMartin so you can remove the step 2 from the README as well, right? :)

**Comment by xMartin** [comment]
Yes, thanks for the heads up!
