### ISSUE TITLE
Make more visible who paid

### ISSUE THREAD

**Issue by jancborchardt** [xMartin/grouptabs#115]
Currently the transaction list has some info in the second row on who participated and who paid. I noticed sometimes it’s hard to see who actually paid, among all the numbers and names. Especially direct transactions are very difficult to make out. What about this before & after:

![capture du 2017-03-01 21-51-40](https://cloud.githubusercontent.com/assets/925062/23480951/0da072a6-feca-11e6-8235-be6022f62389.png) ![capture du 2017-03-01 21-54-06](https://cloud.githubusercontent.com/assets/925062/23480955/0f0e3cf4-feca-11e6-9917-a1834be872b1.png)

Highlight logic is that whoever paid more than their part will be bolded. :)

**Comment by xMartin** [comment]
I like the idea and the design is also good. Still, I'm a bit concerned it can be confusing (not self-explanatory when it's bold).

The direct transactions are still a hack (#45). That doesn't count.

**Comment by xMartin** [comment]
Should we just make bold everyone that paid *something*?

**Comment by xMartin** [comment]
@jancborchardt By the way, looking forward to having this party! ;) Putting aside the 230 already.

**Comment by jancborchardt** [comment]
Yeah, bolding everyone who paid anything (except negative) would be a good improvement for sure. :)
