### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by hugoroy** [xMartin/grouptabs#119]
Hello! Sorry if this is obvious, but I recently lost some of the tabs I opened. No worries as I could find the tab ID again by searching through emails, but then this raises the question. How do I login to some account so I can keep track of that data?

**Comment by xMartin** [comment]
This is currently not implemented but exists on a concept level: https://github.com/xMartin/grouptabs/wiki/Using-the-app-and-sharing-data#story-1

**Comment by hugoroy** [comment]
↪ xMartin / mars 5, 2017 16:32:
> This is currently not implemented but exists on a concept level: https://github.com/xMartin/grouptabs/wiki/Using-the-app-and-sharing-data#story-1

OK, I thought I missed something. So I’d better save somewhere a list of
the tab IDs I care about!

**Comment by xMartin** [comment]
Yes, that's what I do, too. I know this can be a problem. We're also planning on having the ID of a tab in the URL so you can also find it in browser history.

**Comment by hugoroy** [comment]
↪ xMartin / mars 6, 2017 1:32:
> Yes, that's what I do, too. I know this can be a problem. We're also planning on having the ID of a tab in the URL so you can also find it in browser history.

Makes sense!
