### ISSUE TITLE
Possibility to hide technical npm install messages

### ISSUE THREAD

**Issue by jancborchardt** [xMartin/grouptabs#121]
Currently when you do npm install you see this:

```
jan@Rechenknecht:~/grouptabs$ npm install

> grouptabs-app@ postinstall /home/jan/grouptabs
> npm run config:copy


> grouptabs-app@ config:copy /home/jan/grouptabs
> if [ ! -f './js/config.js' ]; then cp ./js/config-sample.js ./js/config.js; fi

jan@Rechenknecht:~/grouptabs$
```
It’s a lot of technical info, about the postinstall and the config:copy command running. You don’t really need to know that if it’s successful. Is it possible to hide that output / run the command silently?

**Comment by xMartin** [comment]
There's the `--silent` option but then you don't get any output at all.

P.S. @jancborchardt "Rechenknecht" :)

**Comment by jancborchardt** [comment]
Damn … where’s `--half-silent` :0
