### ISSUE TITLE
In 2-person tab, prevent un-joining participants

### ISSUE THREAD

**Issue by jancborchardt** [xMartin/grouptabs#123]
If there are just two people in a tab, especially permanently, it sometimes happens that the »joined« button is misclicked and thus the person deselected. This could be disabled to catch misclicks.

Yes there is the case where you want to go through the list and unjoin people before you add the others which took part. A different proposal could be that if you have just two people in a tab and save a transaction with one person not having joined, automatically both should be set to joined cause a transaction with just one person is not possible.

What do you think @xMartin?

**Comment by xMartin** [comment]
How would the toggle button look like for this state "selected and deselection disabled"? It would be confusing if it looked the same but wouldn't react in tap/click, no?

**Comment by jancborchardt** [comment]
I'm now leaning towards the second proposal from above:

> A different proposal could be that if you have just two people in a tab and save a transaction with one person not having joined, automatically both should be set to joined cause a transaction with just one person is not possible.

**Comment by xMartin** [comment]
If you only have two people in a tab, they are both set to "joined" initially for a new transaction.

I don't feel fixing "misclicks" in a certain situation is worth introducing automagic behavior. Is it really that big of an issue?

**Comment by jancborchardt** [comment]
I probably have that once a month or less. So yeah it’s not really that often, but it’s not something that should happen either?

**Comment by jancborchardt** [comment]
I didn’t have this issue since then, so let’s close it. :)
