### ISSUE TITLE
In add/edit form make participant name bold if status is "paid"

### ISSUE THREAD

**Issue by xMartin** [xMartin/grouptabs#133]
Would make this important status stronger and also be consistent with the transaction list where paid participants are also bold.

**Comment by xMartin** [comment]
Makes sense although it might also cause more visual noise. We can try it out.

Another idea: work with green and red somehow to indicate the effect of the transaction for each participant.

**Comment by xMartin** [comment]
Closing this. It's done.

@jancborchardt What do you think about my red/green idea above?

**Comment by jancborchardt** [comment]
Seems good with the red/green. People who paid more equal or more than they needed have their name colored green, people who paid less have their name colored red?
