### ISSUE TITLE
Accidentally put in shared tab ID into new tab name input

### ISSUE THREAD

**Issue by ogasser** [xMartin/grouptabs#136]
I wanted to open a shared tab using the provided ID. I accidentally put it in the new tab input field resulting in a new tab with a bogus name. Only when going back again I saw the "open shared tab" link.

**Comment by xMartin** [comment]
Duplicate of #104 

I bet @jancborchardt told you to file this ;)

**Comment by jancborchardt** [comment]
> I bet @jancborchardt told you to file this ;)

@xMartin BUSTED :D but it did happen and was annoying.
