### ISSUE TITLE
Show tab ID for sharing also on empty tab screen

### ISSUE THREAD

**Issue by xMartin** [xMartin/grouptabs#137]
On the main screen that shows the overview and transactions of one tab we display the tab ID for sharing but it is missing in case you have zero transactions, typically when you just created a tab.

Thanks for reporting, @jancborchardt

**Comment by jancborchardt** [comment]
Yup! Would be ideal to put it as a sticky footer so it doesn’t take too much focus away from the main text and the »Add transaction« button.

**Comment by xMartin** [comment]
Opened #138 for the sticky footer thing.
