### ISSUE TITLE
Export tabs

### ISSUE THREAD

**Issue by MorrisJobke** [xMartin/grouptabs#151]
It would be helpful to export all transactions of a tab into a standard format (CSV for example).

Use case behind this: After a vacation all transactions (maybe with some keywords, by a person, etc) could be used to check against credit card transactions from your bank to check if all of them are valid.

**Comment by xMartin** [comment]
Thanks for your input! I get the idea and I can see the use-case but I'm against implementing this. Grouptabs is supposed to be a simple and fun experience among people that trust each other that makes you think less about money if you're using it than if you don't. There's a lot of [other great products](https://github.com/xMartin/grouptabs/wiki/Competition-and-Inspiration) out there that offer reporting features and a lot more.
