### ISSUE TITLE
Sorting of tabs

### ISSUE THREAD

**Issue by jancborchardt** [xMartin/grouptabs#158]
Currently the main tab list does not seem to be sorted in any way. That’s quite confusing, as there’s no anchor, and it might be different on different devices too.

It would be best to sort the list by having the tabs with the most recent transaction first. What do you think @xMartin?

**Comment by xMartin** [comment]
I think this can be useful. I wonder if it could also be confusing as no transaction or date is shown there.

**Comment by jancborchardt** [comment]
Let’s just start out with one way of sorting. ;) If we want an indicator, we could add a second row either with last transaction, or a summary of the standing?

**Comment by xMartin** [comment]
@jancborchardt Most recent meaning last added/edited or date of the transaction happening?

**Comment by xMartin** [comment]
Going with most recent date of transaction for now.

@jancborchardt sounds also like what you initially intended.

**Comment by jancborchardt** [comment]
NO WAY, finally nice sorting! :D :heart: you @xMartin
