### ISSUE TITLE
Simplify summary in transaction list

### ISSUE THREAD

**Issue by xMartin** [xMartin/grouptabs#170]
We could only show amounts in the small text below the description for the case that multiple people paid. Otherwise we show the same number in big on the right anyway.

@jancborchardt What do you think? Reduce noise or be consistent?

**Comment by xMartin** [comment]
Hm, that way it is only indicated by bold font who paid - not really clear.

**Comment by jancborchardt** [comment]
Good question – I’d agree that it’s not really clear if there’s no number, and it’s better to be consistent. That way bold always means "paid" and you also learn it through the amount shown there.

**Comment by xMartin** [comment]
Cool, thanks, closing then. I guess I was a bit too fast, optimizing ;)
