### ISSUE TITLE
TLS certificate on backend.grouptabs.net has expired

### ISSUE THREAD

**Issue by nikolaplejic** [xMartin/grouptabs#192]
Hello folks,

the certificate on https://backend.grouptabs.net/ has expired 5 days ago. Consequently, nothing syncs at the moment unless you know how to explicitly add an exception for the domain in your browser. Let me know if there's any other information I can provide.

Thanks!

**Comment by xMartin** [comment]
Thank you so much for the report. I fixed it.

Need to take some time to correctly automate updating the certificate. This way at least I know someone is actually using the app ;)=

**Comment by nikolaplejic** [comment]
@xMartin Hey, sorry to reopen this one, but the certificate seems to have expired again. :) Any chance you could take a look?

If you need any help in setting up auto-renewal, I'd be glad to lend a hand. Thanks!

**Comment by xMartin** [comment]
Fixed. Sorry about that again. I do have an automation in place that seems to have issues. Fixed permissions so hope next times it works.
