### ISSUE TITLE
Transaction list scrolls back to top again after creating a new transaction

### ISSUE THREAD

**Issue by jancborchardt** [xMartin/grouptabs#205]
When you scroll down in the transaction list and create a new transaction, after saving it you get thrown back to the top of the transaction list.

This does not happen when viewing or editing an existing transaction, where going back or saving preserves the scroll position, as expected.

This is very annoying for example when you put in expenses from some time ago, where you check if you or friends already put in an expense, and then you need to scroll back down after each new expense you put in.

**Comment by xMartin** [comment]
Agreed. This was implemented assuming an added transaction would likely end up at the top of the list but just keeping the scroll position is probably more likely to help the user than that. Same for deleting transactions by the way.
