### ISSUE TITLE
Feature request: Pay without joining

### ISSUE THREAD

**Issue by TanTrisGit** [xMartin/grouptabs#211]
Maybe this already works, but the way the buttons are displayed it is impossible to determine: I would like to add a transaction where someone paid something for other people, but did not join themselvses.

I apologise if this already is a feature, I did not figure out how to do it (because the "paid" button always hides the "joined" button if you enter something there)

**Comment by xMartin** [comment]
Thanks again for your input! You're correct, this feature doesn't exist. You can either pay for something you're part of or you can pay/give money to one person. It was a conscious decision to not include this for two reasons:

1. I believe adding this would make the UI more complex for a rather rare case
2. This app is focussing on sharing expenses and simplicity

If you see a way to implement this in a very simple way, I will reconsider.
