### ISSUE TITLE
use human dates

### ISSUE THREAD

**Issue by jancborchardt** [xMartin/grouptabs#3]
Currently the date is, say »06.11.2012«. Instead it should be human-readable, like »6 November 2012«.

Maybe even better, and also good for the transaction list: use relative dates, there’s also a great library for that: http:///momentjs.com

**Comment by xMartin** [comment]
Implemented "Today" and "Yesterday". Makes it consistent with #42 . All other cases still use `Date.toLocaleDateString()` so it's OS and browser dependent.

**Comment by xMartin** [comment]
I think the current implementation is good enough.
