### ISSUE TITLE
possible to create tab without title or participants

### ISSUE THREAD

**Issue by jancborchardt** [xMartin/grouptabs#35]
We need some validation, and probably also disable the save button until there’s a title and participants.

**Comment by xMartin** [comment]
Maybe just an alert as a quick fix.

How about
> Please fill in all fields and have at least two participants and one person who paid.
> [OK]

**Comment by jancborchardt** [comment]
If there’s no info at all in the tab, going back should simply not save it. And only deactivating the Save button is also a quick fix, no?

**Comment by xMartin** [comment]
> And only deactivating the Save button is also a quick fix, no?
I don't like the idea of not giving any feedback what is wrong.

**Comment by xMartin** [comment]
Implemented with the alert.
