### ISSUE TITLE
Soft keyboard switching on and off in form

### ISSUE THREAD

**Issue by xMartin** [xMartin/grouptabs#41]
When switching between input fields the soft keyboard on mobile (iOS, FirefoxOS) hides and shows instead of just staying active when focus is on any input. Really annoying.

The problem is the Dijit form widgets: https://bugs.dojotoolkit.org/ticket/17540

**Comment by jancborchardt** [comment]
Can’t reproduce on Firefox mobile anymore. Can you check again if this is fixed on iOS too @xMartin?

**Comment by xMartin** [comment]
Nobody is working on the remoteStorage version at the moment.
