### ISSUE TITLE
Add date buttons for "today" and "yesterday" in addition to date picker

### ISSUE THREAD

**Issue by xMartin** [xMartin/grouptabs#42]
In order to make the most used options for date entry easier accessible, add buttons for "today" and "yesterday" in addition to the date picker. These could all be in one line next to each other. "Today" would be selected by default. Additionally there could be a display in the buttons or below the line of buttons showing the actual selected date.

**Comment by jancborchardt** [comment]
Here’s a quick mockup with the rest of the new UI:

- Today and yesterday are the most present toggles
- When switching those, the date on the right will reflect that
- You can put in a custom date by just using the date picker on the right :)

![date picker](https://user-images.githubusercontent.com/925062/51999961-3ac5bd80-24bc-11e9-9223-75201a510045.png)

**Comment by xMartin** [comment]
@jancborchardt 🎉 - this has been around for a while... Let's see if it's useful. I know the distribution of the buttons is not nice but i don't see a good way to make sure the date input isn't cut off across platforms.
