### ISSUE TITLE
Direct payments

### ISSUE THREAD

**Issue by xMartin** [xMartin/grouptabs#45]
In practice there's many situations where one person would pay something for someone else that is not shared or just lends some money.

This can be handled by creating a transaction with two participants, the paying person adding the amount in plus, the receiving person having the amount in minus.

There should be a UI for that.

How about a toggle switch below the date field when entering a transaction saying "shared" or "direct". And when "direct" it switches to two fields for the participants with an arrow between to indicate the direction of payment and a field for amount. Same kind of layout could be used for the transaction list.

**Comment by xMartin** [comment]
How about using a native `<select>` element but adding "<new participant>" as the last option? When selected, a new input field is added below. Not really beautiful, but could work.

**Comment by xMartin** [comment]
Another idea to work around the "select + new" problem and also keep more to the design of the shared transaction:

![direct v2](https://cloud.githubusercontent.com/assets/112532/20029580/f97f8fbc-a34f-11e6-8ab5-a3b6b454df7f.jpg)

Only one "from" button and one "to" button can be selected at a time (behavior like radio groups). Selecting "from" changes the "to" button to an input field for the amount.

@jancborchardt

**Comment by xMartin** [comment]
Change label "From" to "paid" and "To" to "got" so we stay with the current wording.

**Comment by jancborchardt** [comment]
@xMartin just checking out the prototype :) What is _very_ confusing at the moment is that whenever you switch between »Direct« and »Shared«, the whole app reloads. (Just makes testing very irritating. ;)

**Comment by xMartin** [comment]
Seems to be happening in Firefox but not Chrome. Will check.

**Comment by jancborchardt** [comment]
Design enhancement for the dropdown toggle: https://github.com/xMartin/grouptabs/tree/direct-transaction-design

**Comment by jancborchardt** [comment]
Slow but steady! 🐢
