### ISSUE TITLE
make it more intuitive to indicate a person receives or spends money

### ISSUE THREAD

**Issue by silverbucket** [xMartin/grouptabs#47]
By default the amount entered is a negative amount, which means that - for example, if someone receives money, you'd have to put -[amount] which seems counter intuitive.

The way I think about it, when I'm looking at a list of people and amounts. + would mean they received it, and - would mean they paid it. which is the opposite of how it behaves right now.

**Comment by xMartin** [comment]
This request hasn't popped up again. The app's clear focus is on spending money.
