### ISSUE TITLE
Add visual cue that numbers are representing money

### ISSUE THREAD

**Issue by xMartin** [xMartin/grouptabs#64]
As we're removing currency symbols and decimal places for simplicity and friendliness it would help if we come up with some kind of symbol or something to show that the numbers represent money.

@jancborchardt ?

**Comment by jancborchardt** [comment]
We also thought about a "money" icon but it doesn’t really look good unless in color – but then it’s too much when every entry has it:
![grouptabs currency](https://user-images.githubusercontent.com/925062/59967034-08793300-9525-11e9-84a2-cf56b490442d.png)

The "money" icons in The Noun Project: https://thenounproject.com/search/?q=money – also are only recognizable when they have a dollar icon, and then it’s very specific and we could just use the $ symbol.

**Comment by jancborchardt** [comment]
Closing this in favor of https://github.com/xMartin/grouptabs/issues/65#issuecomment-39762638
