### ISSUE TITLE
Loading screen

### ISSUE THREAD

**Issue by jancborchardt** [xMartin/grouptabs#74]
When opening Grouptabs or starting Grouptabs in the tabs view, oftentimes for a few seconds only the help text is shown. Only then the values are loaded and put in.

A simple spinner in the main content area would be helpful to show stuff is loading.

**Comment by xMartin** [comment]
Done. 1ebc05994b6544e7a007e41bbf48ea73fd0960db

**Comment by jancborchardt** [comment]
Very cool! :)
