### ISSUE TITLE
Ability to check total money spent

### ISSUE THREAD

**Issue by jancborchardt** [xMartin/grouptabs#75]
Currently only the relative amounts between the people are visible. It would be nice to have a way to see the absolute total of money spent, by person. (Maybe even restrict it to a time frame, for example »last two weeks« for the vacation usecase.)

This might make most sense in the detail view of a person, where also the per-person breakdown (see https://github.com/xMartin/grouptabs/issues/25) should be shown.

What do you think @xMartin? cc @insaw

**Comment by ogasser** [comment]
The total amount of money spent would be very helpful indeed. Especially for travelling this could give interesting insights (how much money did our trip to Croatia cost).

I understand the "hiding numbers and money as much as possible", but this simple figure (e.g. " Total spent: 123.45") displayed below the bottom most expense and directly above the "Share..." would be very helpful!

**Comment by xMartin** [comment]
@ogasser Thanks for your input. I like the idea how to display it in an unobtrusive way.

**Comment by xMartin** [comment]
I impemented it like so:
<img width="552" alt="Total Spending" src="https://user-images.githubusercontent.com/112532/59979252-99afde80-95e5-11e9-9d80-6b32b2bc5887.png">

I'm still not a fan of displaying it permanently. Maybe we can come up with some "detail" or "report" view that the user can open. Anyway, will merge it like that and the we can see if we like it or not.

**Comment by MorrisJobke** [comment]
Thanks a lot @xMartin 🚀

**Comment by jancborchardt** [comment]
Gotta love the rude awakening when you scroll to the end and realize how much you spent … 💸
