### ISSUE TITLE
Ability to hide old records

### ISSUE THREAD

**Issue by silverbucket** [xMartin/grouptabs#87]
We are dusting off our hackerbeach 5apps account and starting to use grouptabs to track expenses, but we have a bunch of old transactions from last years hackerbeach that we don't want to see.

The only thing we can do right now is to manually delete the grouptabs data from 5apps, but this is obviously not ideal. Would be nice to set a hide flag on things you don't want to see anymore.

**Comment by xMartin** [comment]
My idea here was to just start a new tab ("Hacker Beach 2015"). The old data would only appear in the tab list. And yes, it should be possible to remove tabs...
