### ISSUE TITLE
Update remoteStorage.js to 0.11.2

### ISSUE THREAD

**Issue by skddc** [xMartin/grouptabs#88]
We fixed a bug that breaks the widget state updating, resulting in the icon not flashing when updating. I'm missing it especially on the Grouptabs dashboard, when waiting for new transactions to come in.

https://community.remotestorage.io/t/remotestorage-js-0-11-2-released/267

By the way, thanks so much for this app! Super useful whenever I'm travelling with a buddy. ;)

**Comment by xMartin** [comment]
Done (https://github.com/xMartin/grouptabs/commit/31f8639860860b5a59e9aab65e76985985838201).

Super happy it's useful for you!

**Comment by skddc** [comment]
![thumbs-up-cool2](https://cloud.githubusercontent.com/assets/842/6655943/8858b1ae-cb0d-11e4-99ad-cc1d2610aaca.gif)
