### ISSUE TITLE
Rename "import" to "open"

### ISSUE THREAD

**Issue by xMartin** [xMartin/grouptabs#89]
> How about saying "open shared tab" instead of "import"?
– @skddc

I think it's a good idea as "import" is very technical.

**Comment by skddc** [comment]
Also, I thought it means importing my tabs from the current production version. In fact, it looked to me like shared tabs aren't even possible, until after I added the first transaction and saw the ID shown.

**Comment by xMartin** [comment]
I see. An import in that sense is not planned. Could be a dedicated app.

Importing currently means either opening a tab you created on another device/browser or that someone shared with you. "Open shared tab" could work as long as you understand you can also share with yourself...

As for communicating the possibility of sharing, we need a UI for that: #91
