### ISSUE TITLE
Kassen-sharing

### ISSUE THREAD

**Issue by jancborchardt** [xMartin/grouptabs#9]
It should be possible to share Kassen, as a start read-only.

For that there could be a share button in the top right of the Kasse detail view, which when clicked gives you a public link in the manner of gruppenkasse.com/#user@host/kassenname

This will look almost exactly like the Kasse detail view, except with nothing editable and without the buttons for »< Kassen«, »share« and »+ New transaction«.

**Comment by jancborchardt** [comment]
@xMartin we didn’t discuss this, do we still want it? Doesn’t seem like it ever came up again.

**Comment by xMartin** [comment]
Would be super cool to have it but I don't want to work on the remoteStorage branch at the moment.
