### ISSUE TITLE
Autocomplete for transaction description 

### ISSUE THREAD

**Issue by jancborchardt** [xMartin/grouptabs#98]
When tapping on the description field, we could open an autocomplete dropdown with the most frequently used titles. That would help if you use the same title a lot. Like »Volleyball« or »Beers«.

**Comment by xMartin** [comment]
Need to research auto-complete inputs that are a pleasure on mobile.

**Comment by xMartin** [comment]
To be more specific: suggest all descriptions already used in that tab, ordered by how many times they've been used.

**Comment by jancborchardt** [comment]
Closing in favor of **Simpler way to input description than a text field (categories / icons) #80**
